version: 1
formatters:
        brief:
            format: '%(message)s'
        default:
            format: '[%(asctime)s][%(levelname)s] %(message)s'
        debugging:
            format: '[%(asctime)s][%(levelname)s][%(module)s.%(funcName)s.%(lineno)s] %(message)s'
handlers:
        console:
                formatter: default
                class: logging.StreamHandler
                stream: ext://sys.stdout
root:
    handlers: [console]
    level: INFO
